services:
  ollama-service:
    image: ollama/ollama:latest
    # build: 
    #   context: .
    #   dockerfile: ollama.dockerfile
    env_file:
      - .env
    environment:
      - OLLAMA_MODELS=${OLLAMA_MODELS}
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: 1
    expose:
      - 11434
    ports:
      - 11434:11434
    
    healthcheck:
      # base ollama does not include curl, needs to be rebuilt
      test: "${DOCKER_HEALTHCHECK_TEST:-curl http://localhost:11434/}" 
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - devika-subnetwork

  devika-backend-engine:
    image: backend
    build:
      context: .
      dockerfile: base.dockerfile
      target: engine
    depends_on:
      - ollama-service
    expose:
      - 1337
    ports:
      - 1337:1337
    environment:
      # ollama will be accessible on the internal subnetwork using hostname  "ollama-service"
      - OLLAMA_HOST=http://ollama-service:11434
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl http://localhost:1337/}"
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      # persist the whole devika folder, including db/projects etc
      - devika-backend-data:/home/nonroot
      # use separate volume for project output
      # volume created as bind mount for easy access in VS Code on Windows
      - devika-projects:/home/nonroot/data/projects
    networks:
      - devika-subnetwork

  devika-frontend-app:
    image: frontend
    build:
      context: .
      dockerfile: base.dockerfile
      target: app
      args:
        - VITE_API_BASE_URL=http://127.0.0.1:1337
    depends_on:
      - devika-backend-engine
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - devika-subnetwork

networks:
  devika-subnetwork:

volumes:
  devika-backend-data:
    external: true
  devika-projects:
    external: true
  ollama:
    external: true